name: Python Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'

